package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;

import java.io.IOException;

import controllers.FeedbackController;
import controllers.SessieController;
import domein.Feedback;
import domein.Sessie;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class FeedbackLijstController extends VBox implements DeelScherm<SessieKalenderDeelScherm> {
	@FXML
	private Button btnGaTerug;
	@FXML
	private Label lblNaam;
	@FXML
	private TextField txfSearch;
	@FXML
	private Button btnMaakLeeg;
	@FXML
	private TableView<Feedback> tableFeedback;
	@FXML
	private TableColumn<Feedback,String> colNaam;
	@FXML
	private TableColumn<Feedback,String> colTijd;
	@FXML
	private TableColumn<Feedback,String> colRating;
	private String zoekWaarde;
	private FeedbackController fc;
	private SessieKalenderDeelScherm parent;
	private SessieController sc;

	@Override
	public void buildGui(SessieKalenderDeelScherm parent) {
		this.parent = parent;
		this.sc = parent.getSessieController();
		this.fc = parent.getFeedbackController();
		Sessie s =sc.getSessie();
		fc.setGekozenSessie(s);
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/FeedbackLijst.fxml"));
		loader.setController(this);
		loader.setRoot(this);
		try {
			loader.load();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		lblNaam.setText(s.getNaam());
		btnMaakLeeg.setDisable(true);
		tableFeedback.setItems(fc.getFeedbackObservableLijst());
		colNaam.setCellValueFactory(cel -> cel.getValue().getNaamProperty());
		colTijd.setCellValueFactory(cel -> cel.getValue().getTijdToegevoegdProperty());
		colRating.setCellValueFactory(cel -> cel.getValue().getAantalSterrenProperty());
		tableFeedback.getSelectionModel().selectedItemProperty().addListener((obs, oldV, newV) -> {
			fc.setGekozenFeedback(newV);
		});
		this.setVgrow(tableFeedback, Priority.SOMETIMES);
	}
	// Event Listener on Button[#btnGaTerug].onAction
	@FXML
	public void gaTerug(ActionEvent event) {
		parent.changeBack();
	}
	// Event Listener on TextField[#txfSearch].onAction
	@FXML
	public void search(ActionEvent event) {
		zoekWaarde = txfSearch.getText();
		btnMaakLeeg.setDisable(false);
		fc.zoekOpNaam(zoekWaarde);
	}
	// Event Listener on Button[#btnMaakLeeg].onAction
	@FXML
	public void maakLeeg(ActionEvent event) {
		// TODO Autogenerated
		zoekWaarde = "";
		txfSearch.setText("");
		btnMaakLeeg.setDisable(true);
		fc.zoekOpNaam(zoekWaarde);
	}
	
}
