package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;

import controllers.GebruikerController;
import domein.Gebruiker;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.input.KeyEvent;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.scene.control.TableColumn;

public class GebruikerLijstController extends VBox{
	@FXML
	private Button btnToevoegen;
	@FXML
	private Button btnMaakLeeg;
	@FXML
	private TextField txfZoek;
	@FXML
	private TableView<Gebruiker> gebruikerTable;
	@FXML
	private TableColumn<Gebruiker,String> naamCol;
	@FXML
	private TableColumn<Gebruiker,String> gebruikersnaamCol;
	@FXML
	private TableColumn<Gebruiker,String> typeCol;
	@FXML
	private TableColumn<Gebruiker,String> statusCol;
	private GebruikerDeelScherm parent;
	private GebruikerController gc;
	private GebruikerDetailsController details;

	public GebruikerLijstController(GebruikerDeelScherm parent,GebruikerDetailsController details) {
		this.parent = parent;
		this.details = details;
		this.gc=parent.getGebruikerController();
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/GebruikerLijst.fxml"));
		loader.setController(this);
		loader.setRoot(this);
		
		try {
			loader.load();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		gebruikerTable.setItems(gc.getSortedGebruikerLijst());
		naamCol.setCellValueFactory(cel -> cel.getValue().getVolledigeNaamProperty());
		gebruikersnaamCol.setCellValueFactory(cel -> cel.getValue().getGebruikerNaamProperty());
		typeCol.setCellValueFactory(cel -> cel.getValue().getTypeProperty());
		statusCol.setCellValueFactory(cel -> cel.getValue().getStatusProperty());
		gebruikerTable.getSelectionModel().selectedItemProperty().addListener((obs,oldV,newV)->{
			details.bewerkGebruiker();
			gc.setGeselecteerdeGebruiker(newV);
        });
		this.setVgrow(gebruikerTable, Priority.SOMETIMES);
	}

	// Event Listener on Button[#btnToevoegen].onAction
	@FXML
	public void toevoegenGebruiker(ActionEvent event) {
		// TODO Autogenerated
		gebruikerTable.getSelectionModel().clearSelection();
		gc.setGeselecteerdeGebruiker(null);
		details.maakGebruiker();
	}
	@FXML
	public void search(KeyEvent e) {
		String zoekwaarde = txfZoek.getText();
		if(!zoekwaarde.isEmpty()||!zoekwaarde.isBlank()) {
			gc.zoekOpNaam(zoekwaarde);
			this.btnMaakLeeg.setDisable(false);
		}
	}
	@FXML
	public void maakLeeg(ActionEvent event) {
		gc.zoekOpNaam("");
		txfZoek.setText("");
		this.btnMaakLeeg.setDisable(true);
	}

}
