package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import java.io.IOException;

import domein.Gebruiker;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.TableView;
import javafx.scene.layout.VBox;
import javafx.scene.control.TableColumn;

public class GebruikerStatistiekLijstController extends VBox implements DeelScherm<StatistiekScherm> {
	@FXML
	private Button btnSessies;
	@FXML
	private ComboBox<String> chSessiekalender;
	@FXML
	private ComboBox<String> chMaand;
	@FXML
	private TableView<Gebruiker> tbGebruikers;
	@FXML
	private TableColumn<Gebruiker,String> colNaam;
	@FXML
	private TableColumn<Gebruiker,String> colUsername;
	@FXML
	private TableColumn<Gebruiker,String> colType;
	@FXML
	private TableColumn<Gebruiker,String> colStatus;
	private StatistiekScherm parent;
	@Override
	public void buildGui(StatistiekScherm parent) {
		// TODO Auto-generated method stub
		this.parent = parent;
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/GebruikerStatistiekLijst.fxml"));
		loader.setController(this);
		loader.setRoot(this);
		
		try {
			loader.load();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
	}
	// Event Listener on Button[#btnSessies].onAction
	@FXML
	public void swichtSessies(ActionEvent event) {
		// TODO Autogenerated
		parent.reload(21, 19);
	}
	// Event Listener on ComboBox[#chSessiekalender].onAction
	@FXML
	public void switchSessiekalender(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#chMaand].onAction
	@FXML
	public void switchMaand(ActionEvent event) {
		// TODO Autogenerated
	}

}
