package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;

import controllers.SessieController;
import domein.SessieGebruiker;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.input.KeyEvent;
import javafx.scene.layout.VBox;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class InschrijvingLijstController extends VBox implements DeelScherm<SessieKalenderDeelScherm> {
	@FXML
	private Button btnGaTerug;
	@FXML
	private Label lblSessieNaam;
	@FXML
	private TextField txfZoek;
	@FXML
	private Button btnMaakLeeg;
	@FXML
	private TextField txfMaxCap;
	@FXML
	private TextField txfHuidigAantalInschrijving;
	@FXML
	private TableView<SessieGebruiker> tableInschrijvingen;
	@FXML
	private TableColumn<SessieGebruiker,String> colNaam;
	@FXML
	private TableColumn<SessieGebruiker,String> colGebruikersNaam;
	@FXML
	private TableColumn<SessieGebruiker,String> colAanwezigheid;
	@FXML
	private TableColumn<SessieGebruiker,String> colTijd;
	private SessieKalenderDeelScherm parent;
	private SessieController sc;
	@Override
	public void buildGui(SessieKalenderDeelScherm parent) {
		// TODO Auto-generated method stub
		this.parent = parent;
		this.sc = parent.getSessieController();
		sc.vulLijstSessieGebruikers();
		
		FXMLLoader loader = new FXMLLoader(getClass().getResource("InschrijvingLijst.fxml"));
		loader.setController(this);
		loader.setRoot(this);
		
		try {
			loader.load();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		btnMaakLeeg.setDisable(true);
		lblSessieNaam.setText(sc.getSessie().getNaam());
		txfMaxCap.setText(String.format("%d", sc.getSessie().getMaxCap()));
		txfHuidigAantalInschrijving.setText(String.format("%d", sc.getAantalInschrijvingen()));
		
		tableInschrijvingen.setItems(sc.getSessieGebruikersLijst());
		colNaam.setCellValueFactory(cel -> cel.getValue().getVolledigeNaamProperty());
		colGebruikersNaam.setCellValueFactory(cel -> cel.getValue().getGebruikerNaamProperty());
		colAanwezigheid.setCellValueFactory(cel-> cel.getValue().getAanwezigProperty());
		colTijd.setCellValueFactory(cel-> cel.getValue().getTijdProperty());
		tableInschrijvingen.getSelectionModel().selectedItemProperty().addListener((obs, oldV, newV) -> {
			sc.setGeselecteerdeSessieGebruiker(newV);
		});
	}
	// Event Listener on Button[#btnGaTerug].onAction
	@FXML
	public void gaTerug(ActionEvent event) {
		// TODO Autogenerated
		parent.changeBack();
	}
	// Event Listener on TextField[#txfZoek].onKeyReleased
	@FXML
	public void search(KeyEvent event) {
		// TODO Autogenerated
		
		String zoekWaarde = txfZoek.getText();
		btnMaakLeeg.setDisable(false);
		sc.zoekOpNaamSessieGebruiker(zoekWaarde);
		
	}
	// Event Listener on Button[#btnMaakLeeg].onAction
	@FXML
	public void maakLeeg(ActionEvent event) {
		// TODO Autogenerated
		txfZoek.setText("");
		btnMaakLeeg.setDisable(true);
		sc.zoekOpNaamSessieGebruiker("");
	}
	
}
