package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import controllers.SessieController;
import domein.Media;
import domein.MediaType;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.input.KeyEvent;
import javafx.scene.layout.VBox;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class MediaLijstController extends VBox implements DeelScherm<SessieKalenderDeelScherm> {
	@FXML
	private Label lblSessieNaam;
	@FXML
	private TextField txfZoek;
	@FXML
	private Button btnMaakLeeg;
	@FXML
	private Button btnNieuw;
	@FXML
	private Button btnGaTerug;
	@FXML
	private ComboBox<String> cbType;
	@FXML
	private TableView<Media> mediaTable;
	@FXML
	private TableColumn<Media,String> naamCol;
	@FXML
	private TableColumn<Media,String> colTijd;
	@FXML
	private TableColumn<Media,String> colType;
	private SessieController sc;
	private SessieKalenderDeelScherm parent;
	@Override
	public void buildGui(SessieKalenderDeelScherm parent) {
		this.parent = parent;
		this.sc=parent.getSessieController();
		sc.vulLijstMedia();
		FXMLLoader loader = new FXMLLoader(getClass().getResource("MediaLijst.fxml"));
		loader.setController(this);
		loader.setRoot(this);

		try {
			loader.load();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		lblSessieNaam.setText(sc.getSessie().getNaam());
		List<String> mediaLijst = Arrays.asList(MediaType.values()).stream().sorted().map(m->MediaType.MediaTypeToString(m)).collect(Collectors.toList());
		cbType.setItems(FXCollections.observableArrayList(mediaLijst));
		mediaTable.setItems(sc.getMedia());
		naamCol.setCellValueFactory(cel -> cel.getValue().getNaamProperty());
		colTijd.setCellValueFactory(cel -> cel.getValue().getTijdToegevoegdProperty());
		colType.setCellValueFactory(cel -> cel.getValue().getTypeProperty());
		mediaTable.getSelectionModel().selectedItemProperty().addListener((obs,oldV,newV)->{
			sc.setGeselecteerdeMedia(newV);
        });
	}
	// Event Listener on TextField[#txfZoek].onKeyReleased
	@FXML
	public void search(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnMaakLeeg].onAction
	@FXML
	public void maakLeeg(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnNieuw].onAction
	@FXML
	public void nieuwMedia(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#cbType].onAction
	@FXML
	public void changeTypeMedia(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnGaTerug].onAction
	@FXML
	public void gaTerug(ActionEvent event) {
		parent.changeBack();
	}
	
}
