package gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.input.KeyEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class MediaLijstController {
	@FXML
	private Label lblSessieNaam;
	@FXML
	private TextField txfZoek;
	@FXML
	private Button btnMaakLeeg;
	@FXML
	private Button btnNieuw;
	@FXML
	private ComboBox cbType;
	@FXML
	private TableView mediaTable;
	@FXML
	private TableColumn naamCol;
	@FXML
	private TableColumn colTijd;
	@FXML
	private TableColumn colType;

	// Event Listener on TextField[#txfZoek].onKeyReleased
	@FXML
	public void search(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnMaakLeeg].onAction
	@FXML
	public void maakLeeg(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnNieuw].onAction
	@FXML
	public void nieuwMedia(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#cbType].onAction
	@FXML
	public void changeTypeMedia(ActionEvent event) {
		// TODO Autogenerated
	}
}
