package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;
import javafx.scene.layout.VBox;

import java.io.IOException;

import domein.GebruikerType;
import javafx.event.ActionEvent;

public class MenuDeelSchermController extends VBox {

	@FXML
	private Button btnSessieKalender;
	@FXML
	private Button btnRaadPleegStat;
	@FXML
	private Button btnBeheerGebruiker;
	@FXML
	private Button btnAankondiging;
	@FXML
	private Button btnLogout;

	private ApplicatieController parent;

	public MenuDeelSchermController(ApplicatieController parent) {
		this.parent = parent;
		this.getStyleClass().add("rightBorder");
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/MenuDeelScherm.fxml"));
		loader.setController(this);
		loader.setRoot(this);

		try {
			loader.load();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		if (parent.getIngelogdeGebruiker().getType() != GebruikerType.HOOFDVERANTWOORDELIJKE) {
			btnBeheerGebruiker.setDisable(true);
			btnBeheerGebruiker.setVisible(false);
		}

	}
	
	// Event Listener on Button[#btnSessieKalender].onAction
	@FXML
	public void switchSessieKalender(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("SessieKalender");
		parent.update(GuiConstant.SessieKalenderDeelScherm);
	}

	// Event Listener on Button[#btnRaadPleegStat].onAction
	@FXML
	public void switchRaadPleegStat(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("Statistieken");
		parent.update(GuiConstant.StatistiekScherm);

	}

	// Event Listener on Button[#btnBeheerGebruiker].onAction
	@FXML
	public void switchGebruikers(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("Gebruikers");
		parent.update(GuiConstant.GebruikerDeelScherm);
	}

	// Event Listener on Button[#btnAankondiging].onAction
	@FXML
	public void switchAankondiging(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("Aankondigingen");
		parent.update(GuiConstant.AankondigingenDeelScherm);
	}
	
	// Event Listener on Button[#btnLogout].onAction
		@FXML
		public void logout(ActionEvent event) {
			// TODO Autogenerated
			System.out.println("uitgelogd");
			parent.logout();
		}
}
