package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import java.io.IOException;

import controllers.SessieController;
import domein.Sessie;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.layout.VBox;
import javafx.scene.control.ChoiceBox;

import javafx.scene.control.TableColumn;

public class SessieLijstController extends VBox {
	@FXML
	private Button btnNieuweSessieKalender;
	@FXML
	private Button btnVerwijderSessieKalender;
	@FXML
	private ChoiceBox<String> cbAcademiejaar;
	@FXML
	private ChoiceBox<String> cbMaand;
	@FXML
	private TableView<Sessie> tblSessies;
	@FXML
	private TableColumn<Sessie, String> clnTitel;
	@FXML
	private TableColumn<Sessie, String> clnVerantwoordelijke;
	@FXML
	private TableColumn<Sessie, String> clnStartdatum;
	@FXML
	private TableColumn<Sessie, String> clnDuur;

	private SessieController sc;
	private SessieKalenderDeelScherm parent;
	
	public SessieLijstController(SessieKalenderDeelScherm parent) {
		this.parent = parent;
		this.sc = parent.getSessieController();
		FXMLLoader loader = new FXMLLoader(getClass().getResource("SessieLijst.fxml"));
		loader.setController(this);
		loader.setRoot(this);
		
		try {
			loader.load();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
	}
	// Event Listener on Button[#btnNieuweSessieKalender].onAction
	@FXML
	public void maakNieuweSessiekalender(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnVerwijderSessieKalender].onAction
	@FXML
	public void verwijderSessieKalender(ActionEvent event) {
		// TODO Autogenerated
	}
}
