package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.control.TextField;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;

import controllers.SessieController;
import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

import javafx.scene.control.CheckBox;

import javafx.scene.control.DatePicker;

import javafx.scene.control.ChoiceBox;

public class SessieDetailsController extends VBox implements PropertyChangeListener, DeelScherm<SessieKalenderDeelScherm>{
	@FXML
	private DatePicker dtStart;
	@FXML
	private DatePicker dtEind;
	@FXML
	private TextField txfNaam;
	@FXML
	private TextField txfLokaal;
	@FXML
	private ChoiceBox cbVerantwoordelijke;
	@FXML
	private TextField txfStartuur;
	@FXML
	private TextField txfEinduur;
	@FXML
	private TextArea txaBeschrijving;
	@FXML
	private CheckBox chbStaatOpen;
	@FXML
	private CheckBox chbGesloten;
	@FXML
	private HBox hBtns;
	@FXML
	private Button btnMedia;
	@FXML
	private Button btnInschrijvingen;
	@FXML
	private Button btnFeedback;
	@FXML
	private Button btnVerwijder;
	@FXML
	private Button btnOpslaan;
	@FXML
	private Button btnAnnuleer;
	
	private SessieController sc;
	private SessieKalenderDeelScherm parent;
	
	@Override
	public void buildGui(SessieKalenderDeelScherm parent) {
		// TODO Auto-generated method stub
		this.parent = parent;
		this.sc = parent.getSessieController();
		FXMLLoader loader = new FXMLLoader(getClass().getResource("SessieDetails.fxml"));
		loader.setController(this);
		loader.setRoot(this);
		
		try {
			loader.load();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		
	}
	// Event Listener on Button[#btnMedia].onAction
	@FXML
	public void loadMedia(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnInschrijvingen].onAction
	@FXML
	public void loadInschrijvingen(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnFeedback].onAction
	@FXML
	public void loadFeedback(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnVerwijder].onAction
	@FXML
	public void verwijderSessie(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnOpslaan].onAction
	@FXML
	public void opslaan(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAnnuleer].onAction
	@FXML
	public void annuleer(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void propertyChange(PropertyChangeEvent evt) {
		// TODO Auto-generated method stub
		
	}
	
}
