package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import java.io.IOException;

import controllers.SessieController;
import domein.SessieKalender;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.scene.control.DatePicker;

public class SessieKalenderDetailsController extends VBox implements DeelScherm<SessieKalenderDeelScherm> {
	@FXML
	private Label lblSessieKalender;
	@FXML
	private DatePicker dtStart;
	@FXML
	private DatePicker dtEind;
	@FXML
	private Button btnOpslaan;
	@FXML
	private Button btnAnnuleer;
	@FXML
	private Button btnTerug;	
	private SessieController sc;
	private SessieKalenderDeelScherm parent;
	private boolean isNew;
	
	public SessieKalenderDetailsController(boolean isNew) {
		// TODO Auto-generated constructor stub
		this.isNew = isNew;
	}
	@Override
	public void buildGui(SessieKalenderDeelScherm parent) {
		this.parent = parent;
		this.sc = parent.getSessieController();
		FXMLLoader loader = new FXMLLoader(getClass().getResource("SessieKalender.fxml"));
		loader.setController(this);
		loader.setRoot(this);
		
		try {
			loader.load();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		
		if(isNew) {
			SessieKalender sk = sc.getLaasteSessieKalender();
			lblSessieKalender.setText("Nieuwe Sessiekalender");
			dtStart.setValue(sk.getEindDatum());
		}else {
			lblSessieKalender.setText(sc.getGekozenSessieKalender().toString());
			dtStart.setValue(sc.getGekozenSessieKalender().getStartDatum());
			dtEind.setValue(sc.getGekozenSessieKalender().getEindDatum());
		}
		
	}
	// Event Listener on Button[#btnOpslaan].onAction
	@FXML
	public void opslaan(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAnnuleer].onAction
	@FXML
	public void annuleer(ActionEvent event) {
		// TODO Autogenerated
		
	}
	@FXML
	public void gaTerug(ActionEvent event) {
		parent.changeBack();
	}
	
}
