package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.stream.Collectors;

import controllers.StatistiekController;
import domein.Maand;
import domein.Sessie;
import domein.SessieKalender;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;
import javafx.scene.control.SelectionMode;
import javafx.scene.control.TableView;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.scene.control.TableColumn;

public class SessieStatistiekLijstController extends VBox implements DeelScherm<StatistiekScherm> {
	@FXML
	private Button btnGebruikers;
	@FXML
	private Button btnSelecteer;
	@FXML
	private ComboBox<String> chSessiekalender;
	@FXML
	private ComboBox<String> chMaand;
	@FXML
	private TableView<Sessie> tbSessies;
	@FXML
	private TableColumn<Sessie, String> colStart;
	@FXML
	private TableColumn<Sessie, String> colTitel;
	@FXML
	private TableColumn<Sessie, String> colVerantwoordelijke;
	private StatistiekScherm parent;
	private StatistiekController sc;

	@Override
	public void buildGui(StatistiekScherm parent) {
		// TODO Auto-generated method stub
		this.parent = parent;
		this.sc = parent.getStatistiekController();
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/SessieStatistiekLijst.fxml"));
		loader.setController(this);
		loader.setRoot(this);

		try {
			loader.load();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		chSessiekalender.getItems().setAll(sc.getSessieKalenderObservableLijst());
		chMaand.getSelectionModel().select(Maand.of(LocalDate.now().getMonthValue()).toString());
		chMaand.getItems()
				.addAll(Arrays.asList(Maand.values()).stream().map(e -> e.toString()).collect(Collectors.toList()));
		chMaand.getItems().add("--Alles--");
		SessieKalender sk = sc.getGekozenSessieKalender();
		if (sk != null) {
			chSessiekalender.getSelectionModel().select(sk.toString());
		}
		vulTabel();
	}

	private void vulTabel() {
		tbSessies.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);
		tbSessies.setItems(sc.getObsAfgelopenSessiesList());
		colTitel.setCellValueFactory(cel -> cel.getValue().getTitelProperty());
		colVerantwoordelijke.setCellValueFactory(cel -> cel.getValue().getVerantwoordelijkeNaamProperty());
		colStart.setCellValueFactory(cel -> cel.getValue().getStartDatumProperty());
		/*
		 * tbSessies.getSelectionModel().selectedItemProperty().addListener((obs, oldV,
		 * newV) -> { System.out.println("pressed");
		 * sc.setGekozenSessies(tbSessies.getSelectionModel().getSelectedItems());
		 * 
		 * });
		 */
		this.setVgrow(tbSessies, Priority.SOMETIMES);

	}

	// Event Listener on Button[#btnGebruikers].onAction
	@FXML
	public void switchGebruikers(ActionEvent event) {
		// TODO Autogenerated
		parent.reload(20, 22);
	}

	// Event Listener on Button[#btnSelecteer].onAction
	@FXML
	public void selecteer(ActionEvent event) {
		sc.setGekozenSessies(tbSessies.getSelectionModel().getSelectedItems());
	}

	// Event Listener on ComboBox[#chSessiekalender].onAction
	@FXML
	public void switchSessiekalender(ActionEvent event) {
		// TODO Autogenerated
		chMaand.getSelectionModel().clearSelection();
		sc.changeSelectedSessieKalender(chSessiekalender.getSelectionModel().getSelectedItem());
		vulTabel();
	}

	// Event Listener on ComboBox[#chMaand].onAction
	@FXML
	public void switchMaand(ActionEvent event) {
		// TODO Autogenerated
		sc.changeSelectedMaand(chMaand.getSelectionModel().getSelectedItem());
	}

}
